### ISSUE TITLE
获取交易列表时错误

### ISSUE THREAD

**Issue by jeffreyji666** [cryptape/first-forever-demo#15]
![image](https://user-images.githubusercontent.com/2270558/50089704-7d4f7580-0241-11e9-81d5-070d37efa69e.png)

搜了下，说web3.js版本偏高。

**Comment by zengbing15** [comment]
具体问题需要看你发出的请求的返回值, 猜测是合约没有部署好

**Comment by jeffreyji666** [comment]
合约的问题，已关闭
