### ISSUE TITLE
您好！请问我在最后一步编译失败是怎么回事呢？

### ISSUE THREAD

**Issue by coldkillller** [cryptape/first-forever-demo#43]
![image](https://user-images.githubusercontent.com/31784325/66533486-a8df7b80-eb45-11e9-986d-7c3cec8342df.png)

**Comment by kaikai1024** [comment]
请问具体是哪一个步骤呢？

这个有操作吗？
![2019-10-10-101210_686x126_scrot](https://user-images.githubusercontent.com/8768261/66533721-8d28a500-eb46-11e9-92c8-8b8618f03991.png)

**Comment by coldkillller** [comment]
是这样我想先看看web项目运行的效果，我就把整个repo下载到本地了，打算npm start试一下。的确没有修改config.js文件，但是请问一下图中这三个属性应该如何设置呢？十分感谢！
![image](https://user-images.githubusercontent.com/31784325/66535518-64a3a980-eb4c-11e9-9765-065272d2901a.png)

**Comment by kaikai1024** [comment]
需要做这三个步骤：

![2019-10-10-105941_748x395_scrot](https://user-images.githubusercontent.com/8768261/66535754-36729980-eb4d-11e9-88ac-5cf3612b53b0.png)

**Comment by kaikai1024** [comment]
readme 写的可能不是很清晰，需要拆分一下

**Comment by dont-see-big-shark** [comment]
thanks,  add quick start in #55
