### ISSUE TITLE
部署不成功

### ISSUE THREAD

**Issue by blloc** [cryptape/first-forever-demo#5]
1.第一步：
部署智能合约得到的地址为
0x692a70d2e424a56d2c6c27aa97d1a86395877b3a
图片：
![image](https://user-images.githubusercontent.com/8268339/47779673-a751e480-dd34-11e8-92d5-1b37d31b7197.png)

2.第二步：
修改合约地址
![image](https://user-images.githubusercontent.com/8268339/47779738-cea8b180-dd34-11e8-8dac-b7d98f548d7d.png)
不确定是不是只修改这个文件，然后 npm start 就行了，我实际操作了没效果，希望可以得到帮助，跑一下这个 demo。

![image](https://user-images.githubusercontent.com/8268339/47779819-ff88e680-dd34-11e8-997f-4d779fd8cc50.png)

![image](https://user-images.githubusercontent.com/8268339/47781184-0cf3a000-dd38-11e8-908a-9bfc0712e788.png)

![image](https://user-images.githubusercontent.com/8268339/47781194-15e47180-dd38-11e8-86b3-f696ed669f69.png)

**Comment by Keith-CY** [comment]
你这是部署在 remix 的 js vm  里了哦, 部署 first-forever 最简单的方法时在终端的项目目录里执行 yarn run deploy

**Comment by blloc** [comment]
![image](https://user-images.githubusercontent.com/8268339/47848044-02a0d700-de08-11e8-9d0a-ae9610f94c57.png)
还是有问题的
